### ISSUE TITLE
Why are there db_* files in the root directory of the project ?

### ISSUE THREAD

**Issue by tgaff** [phnxdaniel/ex.talk#4]

**Comment by phnxdaniel** [comment]
Those are for me to manage user list since my data is base on the real number so I use them to see the data in MongoDB

**Comment by danielxji6** [comment]
Those are for me to manage user list since my data is base on the real number so I use them to see the data in MongoDB

**Comment by tgaff** [comment]
Are these for seeding?  Maybe they should be moved into a subdirectory for seeds.  It's important to keep your project organized.  As we get into more complex projects the files will be in the hundreds or thousands and we will want to follow conventions for organizing them.
